### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by lucaschain** [codesuki/ecs-nginx-proxy#3]
I had this problem when trying ecs-nginx-proxy, how can I get more debug info?

I saw this when I use docker logs.

```
2017/02/21 01:28:01 found cluster name to be: kanto
2017/02/21 01:28:01 updating config
panic: runtime error: index out of range


goroutine 1 [running]:
panic(0x97b5c0, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*ecsClient).describeCluster(0xc420020248, 0xc420146100, 0x5, 0x9161e0, 0xc420146230, 0xc4200a5b40)
	/go/src/github.com/codesuki/ecs-gen/ecs.go:27 +0x142
main.(*scanner).scan(0xc420159d80, 0xc420159dc0, 0x412bce, 0xc420020248, 0x8, 0x8)
	/go/src/github.com/codesuki/ecs-gen/scanner.go:29 +0xc3
main.updateAndWrite(0xc420020230, 0xc420020248)
	/go/src/github.com/codesuki/ecs-gen/main.go:95 +0x99
main.execute(0xc420020230, 0xc420020248)
	/go/src/github.com/codesuki/ecs-gen/main.go:80 +0x55
main.main()
	/go/src/github.com/codesuki/ecs-gen/main.go:73 +0x1d1
```

**Comment by lucaschain** [comment]
Moved to ecs-gen
